services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - dbm_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./backend/Dbm
      dockerfile: Dockerfile
    ports:
      - "8000:5000"  # Acesse através de http://localhost:8000
    networks:
      - dbm_network
    volumes:
      - ./backend/Dbm:/app
    env_file:
      - ./backend/Dbm/.env
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5077:80"
    networks:
      - dbm_network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  sqlserver_data:

networks:
  dbm_network:
    driver: bridge